baseURL = "https://kalid.io/"
title = "Kalid's blog"
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
#googleAnalytics = "XXX"

# Index   set
[Params]
hello = "Hello,I'm Kalid"
subtitle = "Stay Hungry,Stay Foolish!"
logo = "/img/top_logo.jpg"
favicon ="/img/top_logo.jpg"
share_img = "/img/top_logo.jpg"
dataFormt = "03,08,2018"
commit = false
rss = true
#comments = true
sharebutton = true
baiduKey = "a60715809868679547f5cce7b6866e38"
algolia = "ae7801f6762078eda1af301ce96b6113"
description = "韦世滴,韦世滴的博客|kalid.io"
errorpage = "/img/404.jpg"

# Index big images 
[[Params.bigimg]]
src = "/img/banner1.jpg"
desc = "Spring vitality - February 14, 2018"

[[Params.bigimg]]
src = "/img/banner2.jpg"
desc = "Summer lotus - May 27, 2018"

[[Params.bigimg]]
src = "/img/banner3.jpg"
desc = "Autumn leaves - August 25, 2018"

[[Params.bigimg]]
src = "/img/banner4.jpg"
desc = "Winter plum - December 08, 2017"

# auther info
[Author]
  name = "kalid"
  website = "https://kalid.io/"
  email = "dishuihengxin@gmail.com"
  #facebook = "kalid" 
  github = "dishuihengxin"
  #twitter = "kalid"
  #linkedin = "kalid"
  #500px = "kalid"
  #medium = "kalid"
  #instagram = "kalid"
  weibo = "dishuihengxin"

## main nenu
[[menu.main]]
    identifier = "categories"
    name = "categories"
    weight = 1
	
[[menu.main]]
    parent = "categories"
    name = "Operation"
    url = "categories/operation"
    weight = 1

[[menu.main]]
    parent = "categories"
    name = "Devops"
    url = "categories/devops"
    weight = 2	

[[menu.main]]
    parent = "categories"
    name = "Docker"
    url = "categories/docker"
    weight = 3
	
[[menu.main]]
    parent = "categories"
    name = "Tags"
    url = "tags"
    weight = 4

[[menu.main]]
    identifier = "handbooks"
    name = "Handbooks"
    weight = 2

[[menu.main]]
    parent = "handbooks"
    name = "Gitbook Handbook"
    url = "gitbook-tutorial"
    weight = 1

[[menu.main]]
    name = "About"
    url = "about"
    weight = 3