baseURL = "https://dishuihengxin.github.io/"
title = "Kalid blog website"
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true

# Index   set
[Params]
hello = "Hello,I'm Kalid"
subtitle = "Trying hard to try more open source projects!"
logo = "adress url"
favicon ="images url"
share_img = "images url"
dataFormt = "03,08,2018"
commit = false
rss = true
baidukey = ""
algolia = ""
description = "kalid 的博客|dishuihengxin.github.io"
errorpage = "images url"

# Index big images 
#[[Params.bigimg]]
#src = "url"
#desc = "test #one - Jul 21,2018"

# auther info
[Author]
  name = "kalid"
  website = "https://dishuihengxin.github.io/"
  #email = "dishuihengxin@gmail.com"
  #facebook = "kalid" 
  github = "dishuihengxin"
  #twitter = "kalid"
  linkedin = "kalid"
  #500px = "kalid"
  #medium = "kalid"
  #instagram = "kalid"
  weibo = "kalid"

# 一级菜单
[[menu.main]]
    identifier = "Index"
    name = "Index"
    weight = 1
	
# 二级菜单
[[menu.main]]
    parent = "Index"
    name = "one"
    url = "categories/one"
    weight = 1

[[menu.main]]
    parent = "Index"
    name = "two"
    url = "categories/two"
    weight = 2	
	
[[menu.main]]
    identifier = "Menu2"
    name = "Menu2"
    weight = 2

[[menu.main]]
    identifier = "Menu3"
    name = "Menu3"
    weight = 3
	
	
[[menu.main]]
    name = "About"
    url = "about"
    weight = 4