baseURL = "https://kalid.io/"
title = "Kalid"
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
googleAnalytics = "UA-125790824-1"

[Params]
hello = "Hello,I'm Kalid"
subtitle = "武汉加油！中国加油!"
# subtitle = "Stay Hungry,Stay Foolish!"
logo = "https://res.cloudinary.com/kalid/image/upload/v1569663875/blog/img/avatar-icon.png"
favicon ="https://res.cloudinary.com/kalid/image/upload/v1569664127/blog/img/favicon.ico"
share_img = "https://res.cloudinary.com/kalid/image/upload/v1569663875/blog/img/avatar-icon.png"
dataFormt = "03,08,2018"
commit = false
ad = true
adsense = true
reward = true
baguettebox = true
rss = true
comments = true
#sharebutton = true
baiduKey = "a60715809868679547f5cce7b6866e38"
algolia = "ae7801f6762078eda1af301ce96b6113"
description = "kalid.io"
keywords = ["kalid,kubernetes,docker,linux学习"]
errorpage = "https://res.cloudinary.com/kalid/image/upload/blog/img/404.jpg"

 # bigimg
[[Params.bigimg]]
src = "https://res.cloudinary.com/kalid/image/upload/c_scale,h_195,w_800/v1581567637/blog/img/wuhan-jiayou.jpg"
desc = "致敬医者! - February 13, 2020"

[[Params.bigimg]]
src = "https://res.cloudinary.com/kalid/image/upload/c_scale,h_280,w_800/v1581567155/blog/img/wuhanjiayou.jpg"
desc = "武汉加油！中国加油! - February 13, 2020"

# [[Params.bigimg]]
# src = "https://res.cloudinary.com/kalid/image/upload/c_scale,h_280,w_800/v1577808387/blog/img/happy_new_year.jpg"
# desc = "Happy New Year! - January 01, 2020"

# [[Params.bigimg]]
# src = "https://res.cloudinary.com/kalid/image/upload/c_scale,h_280,w_800/v1577806936/blog/img/happy_new_year_1.jpg"
# desc = "Happy New Year!  - January 01, 2020"


# [[Params.bigimg]]
# src = "https://res.cloudinary.com/kalid/image/upload/v1569727010/blog/img/20190929111541.jpg"
# desc = "Lijiang Snow Mountain - October 02, 2018"

# [[Params.bigimg]]
# src = "https://res.cloudinary.com/kalid/image/upload/v1569727001/blog/img/20190929111455.jpg"
# desc = "Lijiang Snow Mountain - October 02, 2018"

# [[Params.bigimg]]
# src = "https://res.cloudinary.com/kalid/image/upload/v1569727001/blog/img/20190929111516.jpg"
# desc = "Lijiang Snow Mountain - October 02, 2018"

# [[Params.bigimg]]
# src = "https://res.cloudinary.com/kalid/image/upload/blog/img/banner1.jpg"
# desc = "Spring vitality - February 14, 2018"

# [[Params.bigimg]]
# src = "https://res.cloudinary.com/kalid/image/upload/blog/img/banner2.jpg"
# desc = "Summer lotus - May 27, 2018"

# [[Params.bigimg]]
# src = "https://res.cloudinary.com/kalid/image/upload/blog/img/banner3.jpg"
# desc = "Autumn leaves - August 25, 2018"

# [[Params.bigimg]]
# src = "https://res.cloudinary.com/kalid/image/upload/blog/img/banner4.jpg"
# desc = "Winter plum - December 08, 2018"

# Auther info
[Author]
  name = "Kalid"
  website = "https://kalid.io/"
  email = "kalid@kalid.io"
  #facebook = "kalid" 
  github = "dishuihengxin"
  twitter = "kalid_io"
  #linkedin = "kalid"
  #500px = "kalid"
  #medium = "kalid"
  #instagram = "kalid"
  weibo = "dishuihengxin"

## main nenu
[[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "categories"
    name = "categories"
    weight = 2

# [[menu.main]]
#     parent = "categories"
#     name = "kubernetes"
#     url = "categories/kubernetes"
#     weight = 1	

[[menu.main]]
    parent = "categories"
    name = "Operation"
    url = "categories/operation"
    weight = 1

# [[menu.main]]
#     parent = "categories"
#     name = "Docker"
#     url = "categories/docker"
#     weight = 3
	
[[menu.main]]
    parent = "categories"
    name = "Tags"
    url = "tags"
    weight = 4

[[menu.main]]
    parent = "categories"
    name = "Archives"
    url = "archives"
    weight = 5

[[menu.main]]
    identifier = "handbooks"
    name = "Handbooks"
    weight = 3

[[menu.main]]
    parent = "handbooks"
    name = "Gitbook Handbook"
    url = "gitbook-tutorial"
    weight = 1

[[menu.main]]
    name = "About"
    url = "about"
    weight = 4