name: github auto deploy

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    # runs-on: macOS-10.14
    # runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.1
      with:
        hugo-version: '0.58.3'

    - name: Build
      run: hugo --gc --minify

    - name: Deploy
      uses: dishuihengxin/action-deploy@1.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        remote_repo: git@github.com:dishuihengxin/dishuihengxin.github.io.git
        PUBLISH_BRANCH: dev
        PUBLISH_DIR: ./public
